# Generated by Django 3.2.8 on 2021-10-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='SpotName',
        ),
        migrations.RenameModel(
            old_name='Choice',
            new_name='SpotReview',
        ),
    ]
