# Generated by Django 3.2.8 on 2021-10-29 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_auto_20211026_1444'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpotName',
            new_name='SurfSpot',
        ),
    ]
