# Generated by Django 3.2.8 on 2021-10-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0005_surfspot_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surfspot',
            name='author',
        ),
        migrations.AddField(
            model_name='spotreview',
            name='author',
            field=models.CharField(default='unknown author', max_length=30),
        ),
    ]
