# Generated by Django 3.2.8 on 2021-10-29 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_spotname_surfspot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotreview',
            old_name='choice_text',
            new_name='review_text',
        ),
        migrations.RenameField(
            model_name='spotreview',
            old_name='question',
            new_name='surfspot',
        ),
        migrations.RenameField(
            model_name='surfspot',
            old_name='question_text',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='spotreview',
            name='votes',
        ),
    ]
