# Generated by Django 3.2.8 on 2021-10-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20211029_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfspot',
            name='author',
            field=models.CharField(default='unknown author', max_length=30),
        ),
    ]
